AWSTemplateFormatVersion: '2010-09-09'
Description: Parent template that includes a VPC stack as a nested stack.

Parameters:
  VPCName:
    Type: String
    Default: my-vpc
    Description: The name of the VPC.

  CIDRBlock:
    Type: String
    Default: '10.0.0.0/16'
    Description: The CIDR block for the VPC.

  AvailabilityZones:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The list of availability zones to deploy the subnets in.

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/my-bucket/vpc-stack.yaml'
      Parameters:
        VPCName: !Ref VPCName
        CIDRBlock: !Ref CIDRBlock
        AvailabilityZones: !Ref AvailabilityZones

Outputs:
  VPCId:
    Description: "The ID of the VPC"
    Value: !GetAtt VPCStack.Outputs.VPCId

  PublicSubnet1Id:
    Description: "The ID of the first public subnet"
    Value: !GetAtt VPCStack.Outputs.PublicSubnet1Id

  PrivateSubnet1Id:
    Description: "The ID of the first private subnet"
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet1Id

  DBSubnet1Id:
    Description: "The ID of the first DB subnet"
    Value: !GetAtt VPCStack.Outputs.DBSubnet1Id

  PublicSubnet2Id:
    Description: "The ID of the second public subnet"
    Value: !GetAtt VPCStack.Outputs.PublicSubnet2Id

  PrivateSubnet2Id:
    Description: "The ID of the second private subnet"
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet2Id

  DBSubnet2Id:
    Description: "The ID of the second DB subnet"
    Value: !GetAtt VPCStack.Outputs.DBSubnet2Id

  PublicSubnet3Id:
    Description: "The ID of the third public subnet"
    Value: !GetAtt VPCStack.Outputs.PublicSubnet3Id

  PrivateSubnet3Id:
    Description: "The ID of the third private subnet"
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet3Id

  DBSubnet3Id:
    Description: "The ID of the third DB subnet"
    Value: !GetAtt VPCStack.Outputs.DBSubnet3Id